### ISSUE TITLE
lỗi không cài được driver odbc  khi build docker python

### ISSUE THREAD

**Issue by ptuan123987** [tan264/StockTKL#1]
<img width="740" alt="image" src="https://github.com/tan264/StockTKL/assets/87867738/5eb8d45b-3f8d-4ab1-9c7c-a786d430abf7">

t vẫn méo config driver odbc khi t đã tải được odbc-driver 
dockerfile của python : 
<img width="665" alt="image" src="https://github.com/tan264/StockTKL/assets/87867738/45314da2-47c9-4543-b286-204d7dc542db">

**Comment by tan264** [comment]
Hello guys, I got it, but could you please provide me with a video showing the process?

**Comment by ptuan123987** [comment]
I'm sorry, but I can't =)))))

**Comment by ptuan123987** [comment]
I am going to Athena English, waiting for 10:00 pm,

**Comment by tan264** [comment]
> I am going to Athena English, waiting for 10:00 pm,

I see. Even though I am new to Docker, I will try my best to resolve this issue for you.

**Comment by ptuan123987** [comment]
I know that. You are King in my eyes

**Comment by ptuan123987** [comment]
Are you solved? , I hope that it's running

**Comment by tan264** [comment]
Hi there, sorry for my late. However, I hope you understand that I have only less than four hours to learn Docker from scratch and resolve this issue. Fortunately, I finally found a solution for you.

> Dockerfile

```shell
FROM python:3.12.0-slim-bookworm

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY entrypoint.sh ./entrypoint.sh
COPY database.py ./

RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev

# Install MySql ODBC
ADD https://cdn.mysql.com//Downloads/Connector-ODBC/8.2/mysql-connector-odbc-8.2.0-linux-glibc2.28-x86-64bit.tar.gz .
RUN tar -C . -xzvf mysql-connector-odbc-8.2.0-linux-glibc2.28-x86-64bit.tar.gz
RUN cp -r mysql-connector-odbc-8.2.0-linux-glibc2.28-x86-64bit/bin/* /usr/local/bin
RUN cp -r mysql-connector-odbc-8.2.0-linux-glibc2.28-x86-64bit/lib/* /usr/local/lib
RUN myodbc-installer -a -d -n "MySQL ODBC 8.2 ANSI Driver" -t "Driver=/usr/local/lib/libmyodbc8a.so"
RUN myodbc-installer -d -l

# Install python library
RUN pip install --no-cache-dir -r requirements.txt

CMD ["./entrypoint.sh"]
``` 
> entrypoint.sh
```shell
#!/bin/bash
pwd
ls -l
apt
python database.py
``` 
> requirements.txt
```
pyodbc
``` 
In this case, I am testing by using the file 'entrypoint.sh' to execute some commands to demonstrate a successful connection to the database.
File database.py has some changes for testing.

> database.py
```python
import pyodbc

class Database:
    def __init__(self):
        self.server_name = 'host.docker.internal'
        self.database_name = ''
        self.port = '3306'
        self.username = 'root'
        self.password = ''
        self.driver= 'MySQL ODBC 8.2 ANSI Driver'                
        self.connection_string = ('DRIVER={driver};'
                                  'SERVER={server_name},{port};'
                                  'DATABASE={database_name};'
                                  'UID={username};'
                                  'PWD={password};TrustServerCertificate=Yes;MULTI_HOST=1'
                                  'charset=utf8mb4').format(
                                        driver=self.driver,
                                        server_name=self.server_name,
                                        port=self.port,
                                        database_name=self.database_name,
                                        username=self.username,
                                        password=self.password
                                    )    
        print("Connection String:", self.connection_string)
        try :
            self.conn = pyodbc.connect(self.connection_string)
            self.conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
            self.conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
            self.conn.setencoding(encoding='utf-8')
            self.cursor = self.conn.cursor() 
            print("Connection success") 
        except pyodbc.Error as e:
            print("Connection failure") 
            print(e)
        

    def execute_query(self, query, params):
        self.cursor.execute(query, params)
        self.conn.commit()

if __name__ == "__main__":
    Database()
``` 

> "Setting [self.server_name = 'host.docker.internal'] can help you test the connection to the MySQL server on your physical machine."

**Comment by tan264** [comment]
Furthermore, here are some sites I read to solve this issue. Hope this help
[Install MySql ODBC](https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-installation-binary-unix-tarball.html)
[How to use "cp" command to copy folder in Linux correctly](https://stackoverflow.com/questions/68590463/linux-installing-mysql-odbc-driver-error)
[How to connect to mysql server in physical machine from container](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)
